# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 12:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('notes', models.TextField(blank=True, null=True)),
                ('video_link', models.URLField()),
                ('is_timed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('notes', models.TextField()),
                ('length', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('goals', models.TextField()),
                ('periods', models.IntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.TextField()),
                ('is_active', models.BooleanField()),
                ('status', models.CharField(choices=[('development', 'development'), ('active', 'active'), ('complete', 'complete'), ('cancelled', 'cancelled')], max_length=12)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('time', models.TimeField()),
                ('is_amrap', models.BooleanField()),
                ('is_complete', models.BooleanField()),
                ('reps_done', models.IntegerField()),
                ('time_done', models.TimeField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('notes', models.TextField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Period')),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Workout'),
        ),
        migrations.AddField(
            model_name='phase',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Plan'),
        ),
        migrations.AddField(
            model_name='period',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Phase'),
        ),
    ]
