# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20171021_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='workout',
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.ManyToManyField(to='tracker.Set'),
        ),
    ]
