# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20171021_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
