# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20171021_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
