# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20171021_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='reps_done',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='time_done',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
